### ISSUE TITLE
Add comparison against kd-tree

### ISSUE THREAD

**Issue by RReverser** [cavemanloverboy/fnstw#8]
The somewhat older [`kd_tree`](https://crates.io/crates/kd_tree) crate has mentioned optimisations as well (it uses quickselect, as well as has parallel build via `par_build_by_ordered_float`) so it could be interesting to compare its performance to this implementation, but I noticed it's currently missing in README.

**Comment by cavemanloverboy** [comment]
this library has been deprecated in favor of `bosque`, which is faster
